# Generated by Django 3.1.1 on 2020-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cruduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudUser',
        ),
    ]
