# Generated by Django 3.1.1 on 2020-10-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_cruduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
